name: Release

on:
  release:
    types: [created]

jobs:
  package-extension:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Package BrowserExtension as ZIP
        run: zip -r BrowserExtension.zip BrowserExtension/

      - name: Upload BrowserExtension.zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: BrowserExtension.zip
